#!/bin/bash
set -e

echo "Creating NyayaSatya project structure..."

# Root
mkdir -p .github/workflows

# Supabase
mkdir -p supabase/migrations supabase/functions/send-lawyer-email

# Backend
mkdir -p backend/app/{api/v1,services,middleware,background,utils}
mkdir -p backend/tests
mkdir -p backend/alembic/versions

# Touch all backend files
touch backend/app/__init__.py
touch backend/app/main.py
touch backend/app/config.py
touch backend/app/database.py  # only if needed — Supabase replaces most of this
touch backend/app/supabase_client.py
touch backend/app/dependencies.py
touch backend/app/api/__init__.py
touch backend/app/api/v1/__init__.py
touch backend/app/api/v1/query.py
touch backend/app/api/v1/lawyer_auth.py
touch backend/app/api/v1/user_auth.py
touch backend/app/api/v1/documents.py
touch backend/app/api/v1/health.py
touch backend/app/services/__init__.py
touch backend/app/services/fast_mode.py       # FRIEND fills this
touch backend/app/services/verified_mode.py   # FRIEND fills this
touch backend/app/services/doc_service.py     # FRIEND fills this
touch backend/app/services/lawyer_service.py  # YOU fill this
touch backend/app/middleware/__init__.py
touch backend/app/middleware/rate_limit.py
touch backend/app/middleware/request_id.py
touch backend/app/background/__init__.py
touch backend/app/background/tasks.py
touch backend/app/utils/__init__.py
touch backend/app/utils/geo.py
touch backend/app/utils/file_validation.py
touch backend/tests/conftest.py
touch backend/tests/test_auth.py
touch backend/tests/test_lawyer_registration.py
touch backend/tests/test_query_routes.py
touch backend/pyproject.toml
touch backend/Dockerfile
touch backend/.env.example

# Frontend
mkdir -p frontend/src/{lib,types,api,stores,hooks,components/{layout,query,lawyer,document,admin,ui},pages/{auth,lawyer,admin}}
mkdir -p frontend/public

# Touch all frontend files
touch frontend/src/main.tsx
touch frontend/src/App.tsx
touch frontend/src/lib/supabase.ts
touch frontend/src/lib/database.types.ts    # generated by Supabase CLI
touch frontend/src/types/index.ts
touch frontend/src/api/client.ts
touch frontend/src/api/query.ts
touch frontend/src/api/lawyer.ts
touch frontend/src/api/user.ts
touch frontend/src/stores/useAuthStore.ts
touch frontend/src/stores/useQueryStore.ts
touch frontend/src/hooks/useGeoLocation.ts
touch frontend/src/hooks/useSSE.ts
touch frontend/src/components/layout/Navbar.tsx
touch frontend/src/components/layout/Layout.tsx
touch frontend/src/components/query/ModeToggle.tsx
touch frontend/src/components/query/QueryBox.tsx
touch frontend/src/components/query/AnswerPanel.tsx
touch frontend/src/components/query/CitationCard.tsx
touch frontend/src/components/lawyer/LawyerCard.tsx
touch frontend/src/components/lawyer/LawyerSearch.tsx
touch frontend/src/components/document/DocUpload.tsx
touch frontend/src/components/document/DocResult.tsx
touch frontend/src/components/admin/LawyerVerificationPanel.tsx
touch frontend/src/components/ui/LanguageSelector.tsx
touch frontend/src/components/ui/Button.tsx
touch frontend/src/components/ui/Badge.tsx
touch frontend/src/components/ui/Spinner.tsx
touch frontend/src/components/ui/BottomSheet.tsx   # for mobile modals
touch frontend/src/components/ui/Toast.tsx
touch frontend/src/pages/Home.tsx
touch frontend/src/pages/LawyerFinder.tsx
touch frontend/src/pages/Profile.tsx
touch frontend/src/pages/auth/UserSignUp.tsx
touch frontend/src/pages/auth/UserSignIn.tsx
touch frontend/src/pages/auth/LawyerSignIn.tsx
touch frontend/src/pages/auth/LawyerRegister.tsx
touch frontend/src/pages/lawyer/LawyerPendingPage.tsx
touch frontend/src/pages/lawyer/LawyerDashboard.tsx
touch frontend/src/pages/admin/AdminVerify.tsx
touch frontend/index.html
touch frontend/vite.config.ts
touch frontend/tailwind.config.ts
touch frontend/tsconfig.json
touch frontend/package.json
touch frontend/.env.example

# Corpus (friend's territory — just placeholder)
mkdir -p corpus
touch corpus/README.md

# CI/CD
touch .github/workflows/ci.yml
touch .github/workflows/deploy.yml

touch .gitignore
touch docker-compose.yml
touch README.md

echo "✅ Done. Now run: git init && git add . && git commit -m 'chore: initial project structure' && git push"
