import os
import json
from dotenv import load_dotenv
from sentence_transformers import SentenceTransformer
from pinecone import Pinecone
from pinecone_text.sparse import BM25Encoder
import cohere
from groq import Groq

load_dotenv()

# Initialize clients
pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))
co = cohere.Client(os.getenv("COHERE_API_KEY"))
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
model = SentenceTransformer('mixedbread-ai/mxbai-embed-large-v1')

index_name = "legal-rag-v2"
index = pc.Index(index_name)

# Try loading BM25 Encoder
bm25 = None
bm25_path = "bm25_encoder.json"
try:
    if os.path.exists(bm25_path):
        bm25 = BM25Encoder().load(bm25_path)
    else:
        # It should be generated by ingest.py
        print(f"Warning: {bm25_path} not found. Hybrid search will fail if not generated first.")
except Exception as e:
    print(f"Error loading BM25 encoder: {e}")

def embed_query(text: str) -> list[float]:
    embedding = model.encode(text, normalize_embeddings=True).tolist()
    return embedding

def hyde_expand(query: str, query_type: str = "other") -> str:
    try:
        if query_type == "criminal":
            system_prompt = f"Write a hypothetical paragraph from an Indian legal document that answers: {query}. Include specific terms like section numbers, punishment, death penalty, life imprisonment, culpable homicide, mens rea. Write as actual legal text."
        else:
            system_prompt = f"Write a short paragraph from an Indian legal document that answers: {query}. Write as actual legal text, not as an answer."
            
        completion = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "user", "content": system_prompt}
            ],
            temperature=0.1,
            max_tokens=150
        )
        return completion.choices[0].message.content.strip()
    except Exception as e:
        print(f"HyDE error: {e}")
        return query # Fallback to original query

def hybrid_search(query: str, original_query: str = None, top_k: int = 20, query_type: str = "other") -> list:
    hyde_query = original_query if original_query else query
    # Optimization: Skip HyDE for short queries
    if len(hyde_query.split()) < 10:
        hypothetical_doc = hyde_query
    else:
        hypothetical_doc = hyde_expand(hyde_query, query_type)
        
    dense_vec = embed_query(hypothetical_doc)
    
    if bm25 is None:
        raise Exception("BM25 encoder not loaded. Run ingest_v2.py first.")
        
    sparse_vec = bm25.encode_queries(query)
    
    results = index.query(
        vector=dense_vec,
        sparse_vector=sparse_vec,
        top_k=top_k,
        include_metadata=True
    )
    return results.get("matches", [])

def rerank(query: str, candidates: list, top_n: int = 3, query_type: str = "other") -> list:
    if not candidates:
        return []
    documents = [c["metadata"]["text"] for c in candidates]
    try:
        reranked = co.rerank(
            model="rerank-multilingual-v3.0",
            query=query,
            documents=documents,
            top_n=top_n
        )
        
        if query_type == "consumer":
            filtered_candidates = []
            for r in reranked.results[:top_n]:
                cand = candidates[r.index]
                cand["rerank_score"] = r.relevance_score
                filtered_candidates.append(cand)
        else:
            filtered_candidates = []
            for r in reranked.results:
                if r.relevance_score > 0.2:
                    cand = candidates[r.index]
                    cand["rerank_score"] = r.relevance_score
                    filtered_candidates.append(cand)
        return filtered_candidates
    except Exception as e:
        print(f"Cohere rerank error: {e}")
        # Fallback to vector scores
        filtered = [c for c in candidates if c.get("score", 0) > 0.5]
        return filtered[:top_n]

def compress_chunk(query: str, text: str) -> str:
    # Optimization: Only compress chunks > 500 chars
    if len(text) <= 500:
        return text
        
    try:
        completion = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": "Extract only the sentences from the provided chunk that are relevant to the user's query. If nothing is relevant, output absolutely nothing."},
                {"role": "user", "content": f"Query: {query}\n\nChunk: {text}"}
            ],
            temperature=0.1,
            max_tokens=150
        )
        compressed = completion.choices[0].message.content.strip()
        return compressed if compressed else None
    except Exception as e:
        print(f"Compression error: {e}")
        return text # Fallback to original text

def retrieve(query: str, query_type: str = "other") -> tuple[str, list]:
    # Expand query for better retrieval
    expanded_query = query
    if query_type == "consumer" or any(word in query.lower() 
        for word in ["refund", "product", "defective", 
                     "delivery", "amazon", "flipkart", 
                     "online", "purchase", "damaged", 
                     "replacement", "ecommerce"]):
        expanded_query = query + " Consumer Protection Act 2019 defective goods refund complaint consumer forum"

    # Use expanded_query for hybrid_search, but pass original query for HyDE
    candidates = hybrid_search(expanded_query, original_query=query, top_k=20, query_type=query_type)
    
    # Keep original query for HyDE, but use expanded_query for Cohere reranking
    # Optimization: return top_n=3
    reranked = rerank(expanded_query, candidates, top_n=3, query_type=query_type)
    
    if not reranked:
        return None, []
        
    context_parts = []
    sources_list = []
    
    source_num = 1
    for c in reranked:
        text = c["metadata"]["text"]
        score = c.get("rerank_score", c.get("score", 0))
        
        # Compress top 3 chunks
        if source_num <= 3:
            compressed = compress_chunk(query, text)
            if compressed:
                text = compressed
                
        chunk_context = f"[Source {source_num} | Score: {score:.2f} | {c['metadata'].get('source', 'Legal-Dataset-India')}]\n{text}\n---"
        context_parts.append(chunk_context)
        
        sources_list.append({
            "source_num": source_num,
            "score": float(score),
            "preview": text[:200]
        })
        source_num += 1
        
    if not context_parts:
        return None, []
        
    return "\n\n".join(context_parts), sources_list